"""Initial Full Schema

Revision ID: 6b5f78246604
Revises: 
Create Date: 2026-02-02 01:40:28.254495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b5f78246604'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatar_metas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_type', sa.Enum('VBS', 'LBS', 'LBG', 'VBG', 'LAS', 'LAG', 'VAG', 'VAS', 'DEFAULT', name='matchtype'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_avatar_metas')),
    sa.UniqueConstraint('match_type', name=op.f('uq_avatar_metas_match_type'))
    )
    with op.batch_alter_table('avatar_metas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_avatar_metas_id'), ['id'], unique=False)

    op.create_table('quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('exp_reward', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'ONE_TIME', 'WEEKLY', name='questfrequency'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quests'))
    )
    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quests_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('github_access_token', sa.Text(), nullable=True),
    sa.Column('github_refresh_token', sa.Text(), nullable=True),
    sa.Column('github_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('tutorial_completed', sa.Boolean(), nullable=False),
    sa.Column('total_visits', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_github_id'), ['github_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('avatars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('avatar_meta_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('exp', sa.Integer(), nullable=True),
    sa.Column('growth_stage', sa.Enum('EGG', 'CHILD', 'ADULT', 'MASTER', name='growthstage'), nullable=True),
    sa.ForeignKeyConstraint(['avatar_meta_id'], ['avatar_metas.id'], name=op.f('fk_avatars_avatar_meta_id_avatar_metas')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_avatars_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_avatars')),
    sa.UniqueConstraint('user_id', name=op.f('uq_avatars_user_id'))
    )
    with op.batch_alter_table('avatars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_avatars_id'), ['id'], unique=False)

    op.create_table('blog_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('repository_name', sa.String(length=255), nullable=False),
    sa.Column('theme_type', sa.String(length=50), nullable=False),
    sa.Column('post_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_blog_posts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_posts'))
    )
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_posts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_posts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_posts_repository_name'), ['repository_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_posts_title'), ['title'], unique=False)

    op.create_table('blog_visit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('visitor_ip_hash', sa.String(length=64), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_blog_visit_logs_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_visit_logs')),
    sa.UniqueConstraint('owner_id', 'visitor_ip_hash', 'visit_date', name='unique_daily_visit_log')
    )
    with op.batch_alter_table('blog_visit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_visit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_visit_logs_owner_id'), ['owner_id'], unique=False)

    op.create_table('calendars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('repository_name', sa.String(length=100), nullable=False),
    sa.Column('post_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_calendars_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendars'))
    )
    with op.batch_alter_table('calendars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendars_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendars_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendars_user_id'), ['user_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], name=op.f('fk_chat_messages_receiver_id_users')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_chat_messages_sender_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_id'), ['id'], unique=False)

    op.create_table('daily_gifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('target_date', sa.String(length=10), nullable=True),
    sa.Column('is_opened', sa.Boolean(), nullable=True),
    sa.Column('is_solved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_gifts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_gifts'))
    )
    with op.batch_alter_table('daily_gifts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_gifts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_gifts_target_date'), ['target_date'], unique=False)

    op.create_table('friendships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('addressee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', name='friendstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['addressee_id'], ['users.id'], name=op.f('fk_friendships_addressee_id_users')),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name=op.f('fk_friendships_requester_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_friendships'))
    )
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_friendships_id'), ['id'], unique=False)

    op.create_table('guestbooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_guestbooks_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_guestbooks_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guestbooks'))
    )
    with op.batch_alter_table('guestbooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guestbooks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guestbooks_owner_id'), ['owner_id'], unique=False)

    op.create_table('user_dashboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_visitors', sa.Integer(), nullable=True, comment='블로그 누적 순방문자 수(UV)'),
    sa.Column('today_visitors', sa.Integer(), nullable=True, comment='오늘 방문자 수 (자정 초기화 필요, 선택사항)'),
    sa.Column('tech_stack', sa.JSON(), nullable=True, comment='주 사용 언어 및 기술 스택'),
    sa.Column('github_stats', sa.JSON(), nullable=True, comment='커밋 수, 스타 수 등 깃허브 활동 데이터'),
    sa.Column('last_github_updated_at', sa.DateTime(), nullable=True, comment='깃허브 데이터 마지막 갱신 시점'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_dashboards_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_dashboards')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_dashboards_user_id'))
    )
    with op.batch_alter_table('user_dashboards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_dashboards_id'), ['id'], unique=False)

    op.create_table('user_quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'CLAIMED', name='queststatus'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('weekly_checkin_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], name=op.f('fk_user_quests_quest_id_quests')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_quests_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_quests'))
    )
    with op.batch_alter_table('user_quests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_quests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_quests_quest_id'), ['quest_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_quests_user_id'), ['user_id'], unique=False)

    op.create_table('user_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visitor_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_user_visits_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visitor_id'], ['users.id'], name=op.f('fk_user_visits_visitor_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_visits')),
    sa.UniqueConstraint('visitor_id', 'owner_id', 'visit_date', name='uq_user_visit_daily')
    )
    with op.batch_alter_table('user_visits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_visits_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_visits_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_visits_visit_date'), ['visit_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_visits_visitor_id'), ['visitor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_visits_visitor_id'))
        batch_op.drop_index(batch_op.f('ix_user_visits_visit_date'))
        batch_op.drop_index(batch_op.f('ix_user_visits_owner_id'))
        batch_op.drop_index(batch_op.f('ix_user_visits_id'))

    op.drop_table('user_visits')
    with op.batch_alter_table('user_quests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_quests_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_quests_quest_id'))
        batch_op.drop_index(batch_op.f('ix_user_quests_id'))

    op.drop_table('user_quests')
    with op.batch_alter_table('user_dashboards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_dashboards_id'))

    op.drop_table('user_dashboards')
    with op.batch_alter_table('guestbooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guestbooks_owner_id'))
        batch_op.drop_index(batch_op.f('ix_guestbooks_id'))

    op.drop_table('guestbooks')
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_friendships_id'))

    op.drop_table('friendships')
    with op.batch_alter_table('daily_gifts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_gifts_target_date'))
        batch_op.drop_index(batch_op.f('ix_daily_gifts_id'))

    op.drop_table('daily_gifts')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('calendars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendars_user_id'))
        batch_op.drop_index(batch_op.f('ix_calendars_id'))
        batch_op.drop_index(batch_op.f('ix_calendars_created_at'))

    op.drop_table('calendars')
    with op.batch_alter_table('blog_visit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_visit_logs_owner_id'))
        batch_op.drop_index(batch_op.f('ix_blog_visit_logs_id'))

    op.drop_table('blog_visit_logs')
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_posts_title'))
        batch_op.drop_index(batch_op.f('ix_blog_posts_repository_name'))
        batch_op.drop_index(batch_op.f('ix_blog_posts_id'))
        batch_op.drop_index(batch_op.f('ix_blog_posts_created_at'))

    op.drop_table('blog_posts')
    with op.batch_alter_table('avatars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_avatars_id'))

    op.drop_table('avatars')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_github_id'))

    op.drop_table('users')
    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quests_id'))

    op.drop_table('quests')
    with op.batch_alter_table('avatar_metas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_avatar_metas_id'))

    op.drop_table('avatar_metas')
    # ### end Alembic commands ###
