"""add_daily_checkin_log_table

Revision ID: a9894cf517c1
Revises: 6b5f78246604
Create Date: 2026-02-03 02:12:48.495545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a9894cf517c1'
down_revision: Union[str, Sequence[str], None] = '6b5f78246604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_checkin_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('checkin_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_checkin_logs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_checkin_logs')),
    sa.UniqueConstraint('user_id', 'checkin_date', name='uq_user_checkin_daily')
    )
    with op.batch_alter_table('daily_checkin_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_checkin_logs_checkin_date'), ['checkin_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_checkin_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_checkin_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)

    with op.batch_alter_table('blog_visit_logs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)

    with op.batch_alter_table('daily_gifts', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_gifts', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=True)

    with op.batch_alter_table('blog_visit_logs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=True)

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=True)

    with op.batch_alter_table('daily_checkin_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_checkin_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_checkin_logs_id'))
        batch_op.drop_index(batch_op.f('ix_daily_checkin_logs_checkin_date'))

    op.drop_table('daily_checkin_logs')
    # ### end Alembic commands ###
